### ISSUE TITLE
Add native Webkit libraries

### ISSUE THREAD

**Issue by sgerrand** [sgerrand/alpine-pkg-java-openjfx#2]
The native Webkit libraries will be needed. Enable their compilation by setting `COMPILE_WEBKIT = true` in `gradle.properties`.

**Comment by sgerrand** [comment]
The following packages are required by the `web:compileNativeLinux` build:
* gperf
* libxslt
* ruby

**Comment by sgerrand** [comment]
Throwing an error during the build:
```
In file included from /home/builder/package/src/rt-8u151-b12/modules/web/src/main/native/Source/ThirdParty/icu/source/common/putil.cpp:48:0:
/home/builder/package/src/rt-8u151-b12/modules/web/src/main/native/Source/ThirdParty/icu/source/common/putil.cpp: In function 'int32_t uprv_timezone_51()':
/home/builder/package/src/rt-8u151-b12/modules/web/src/main/native/Source/ThirdParty/icu/source/common/putilimp.h:121:27: error: '__timezone' was not declared in this scope
 #       define U_TIMEZONE __timezone                                                               
                           ^
/home/builder/package/src/rt-8u151-b12/modules/web/src/main/native/Source/ThirdParty/icu/source/common/putil.cpp:638:12: note: in expansion of macro 'U_TIMEZONE'
     return U_TIMEZONE;
            ^~~~~~~~~~       
```

**Comment by aclowkey** [comment]
Any workaround for this? I created an image with OpenJDK 8 and the OpenJFX, and getting the error:

> Exception in thread "JavaFX Application Thread" java.lang.UnsatisfiedLinkError: Can't load library: /usr/lib/jvm/java-1.8-openjdk/jre/lib/amd64/libjfxwebkit.so
> 	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1827)
> 	at java.lang.Runtime.load0(Runtime.java:809)
> 	at java.lang.System.load(System.java:1086)
> 	at com.sun.glass.utils.NativeLibLoader.loadLibraryFullPath(NativeLibLoader.java:201)
> 	at com.sun.glass.utils.NativeLibLoader.loadLibraryInternal(NativeLibLoader.java:94)
> 	at com.sun.glass.utils.NativeLibLoader.loadLibrary(NativeLibLoader.java:39)
> 	at com.sun.webkit.WebPage.lambda$static$0(WebPage.java:131)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at com.sun.webkit.WebPage.<clinit>(WebPage.java:130)
> 	at javafx.scene.web.WebEngine.<init>(WebEngine.java:881)
> 	at javafx.scene.web.WebEngine.<init>(WebEngine.java:868)
> 	at javafx.scene.web.WebView.<init>(WebView.java:273)
> 	at io.webfolder.ui4j.webkit.WebKitBrowser$WebViewCreator.run(WebKitBrowser.java:250)
> 	at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
> 	at com.sun.glass.ui.monocle.RunnableProcessor.runLoop(RunnableProcessor.java:92)
> 	at com.sun.glass.ui.monocle.RunnableProcessor.run(RunnableProcessor.java:51)
> 	at java.lang.Thread.run(Thread.java:748)
> Exception in thread "JavaFX Application Thread" io.webfolder.ui4j.api.util.Ui4jException: java.lang.NullPointerException
> 	at io.webfolder.ui4j.webkit.aspect.WebKitAspect$CallableExecutor.run(WebKitAspect.java:41)
> 	at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
> 	at com.sun.glass.ui.monocle.RunnableProcessor.runLoop(RunnableProcessor.java:92)
> 	at com.sun.glass.ui.monocle.RunnableProcessor.run(RunnableProcessor.java:51)
> 	at java.lang.Thread.run(Thread.java:748)
> Caused by: java.lang.NullPointerException
> 	at io.webfolder.ui4j.webkit.dom.WebKitPage.addDocumentListener_aroundBody4(WebKitPage.java:159)
> 	at io.webfolder.ui4j.webkit.dom.WebKitPage$AjcClosure5.run(WebKitPage.java:1)
> 	at io.webfolder.ui4j.internal.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
> 	at io.webfolder.ui4j.webkit.aspect.WebKitAspect$CallableExecutor.run(WebKitAspect.java:39)
> 	... 6 more
>

**Comment by alvarofernandezavalos** [comment]
> 
> 
> Any workaround for this? I created an image with OpenJDK 8 and the OpenJFX, and getting the error:
> 
> > Exception in thread "JavaFX Application Thread" java.lang.UnsatisfiedLinkError: Can't load library: /usr/lib/jvm/java-1.8-openjdk/jre/lib/amd64/libjfxwebkit.so
> > at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1827)
> > at java.lang.Runtime.load0(Runtime.java:809)
> > at java.lang.System.load(System.java:1086)
> > at com.sun.glass.utils.NativeLibLoader.loadLibraryFullPath(NativeLibLoader.java:201)
> > at com.sun.glass.utils.NativeLibLoader.loadLibraryInternal(NativeLibLoader.java:94)
> > at com.sun.glass.utils.NativeLibLoader.loadLibrary(NativeLibLoader.java:39)
> > at com.sun.webkit.WebPage.lambda$static$0(WebPage.java:131)
> > at java.security.AccessController.doPrivileged(Native Method)
> > at com.sun.webkit.WebPage.(WebPage.java:130)
> > at javafx.scene.web.WebEngine.(WebEngine.java:881)
> > at javafx.scene.web.WebEngine.(WebEngine.java:868)
> > at javafx.scene.web.WebView.(WebView.java:273)
> > at io.webfolder.ui4j.webkit.WebKitBrowser$WebViewCreator.run(WebKitBrowser.java:250)
> > at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
> > at java.security.AccessController.doPrivileged(Native Method)
> > at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
> > at com.sun.glass.ui.monocle.RunnableProcessor.runLoop(RunnableProcessor.java:92)
> > at com.sun.glass.ui.monocle.RunnableProcessor.run(RunnableProcessor.java:51)
> > at java.lang.Thread.run(Thread.java:748)
> > Exception in thread "JavaFX Application Thread" io.webfolder.ui4j.api.util.Ui4jException: java.lang.NullPointerException
> > at io.webfolder.ui4j.webkit.aspect.WebKitAspect$CallableExecutor.run(WebKitAspect.java:41)
> > at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
> > at java.security.AccessController.doPrivileged(Native Method)
> > at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
> > at com.sun.glass.ui.monocle.RunnableProcessor.runLoop(RunnableProcessor.java:92)
> > at com.sun.glass.ui.monocle.RunnableProcessor.run(RunnableProcessor.java:51)
> > at java.lang.Thread.run(Thread.java:748)
> > Caused by: java.lang.NullPointerException
> > at io.webfolder.ui4j.webkit.dom.WebKitPage.addDocumentListener_aroundBody4(WebKitPage.java:159)
> > at io.webfolder.ui4j.webkit.dom.WebKitPage$AjcClosure5.run(WebKitPage.java:1)
> > at io.webfolder.ui4j.internal.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
> > at io.webfolder.ui4j.webkit.aspect.WebKitAspect$CallableExecutor.run(WebKitAspect.java:39)
> > ... 6 more

Did you solve the issue?

**Comment by sgerrand** [comment]
> Did you solve the issue?

I'm afraid not. 😞

**Comment by alvarofernandezavalos** [comment]
I didn't.
I can't compile because de APKBUILDER is borken.
